# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  global:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Node.js environement
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      # Install all needed dependency to run the server
      - name: Install dependency
        run: yarn install --frozen-lockfile

      # Run the database
      - name: Start the database
        run: docker-compose up -d db

      # Coding style
      - name: ESLINT - check coding style
        run: yarn eslint

      # Generate config file
      - name: Generate config file
        run: npm run generate-config

      # Create the table
      - name: Create database table
        run: yarn db:migrate

      # Run the init-data test
      - name: Run Init-data test
        run: yarn init-db

      # Runs a set of commands using the runners shell
      - name: Run test
        run: yarn test
